[workspace]
members = [
    "node/augran",
    "runtime/augran-runtime",
    "node/pow",
    "runtime/pow-runtime",
    "node/bagran",
    "runtime/bagran-runtime",
]
[profile.release]
panic = "unwind"
